### ISSUE TITLE
Adjust Terminated status processing.

### ISSUE THREAD

**Issue by 7R41N33** [UffizziCloud/uffizzi#125]
When a pod has Terminated status a preview should not considered as failed.

Repo for testing this issue:
https://github.com/axisofentropy/uffizzi_chaos

**Comment by zipofar** [comment]
Same task for platform https://github.com/UffizziCloud/uffizzi_platform/issues/16

**Comment by zipofar** [comment]
## How to TEST:
1. Launch ufffizzi core (uffizzi_app). Does not forget add `MANAGED_DNS_ZONE_DNS_NAME: "example.uffizzi.com"` to compose file
2. Launch uffizzi controller
3. Launch uffizzi cli `docker-compose run --rm gem bash`

Use this docker-compose.uffizzi.yaml for create preview `bundle exec uffizzi preview create docker-compose.uffizzi.yaml`

```
services:
  chaos:
    image: dbpterraform2/uffizzi_chaos_exit_until_nginx

  web:
    image: nginx

x-uffizzi:
  ingress:
    service: chaos
    port: 80

  continuous_preview:
    share_to_github: true
    delete_preview_after: 1h
    delete_preview_when_pull_request_is_closed: true
    deploy_preview_when_pull_request_is_opened: true
```

Result should be:
![Screenshot 2022-06-08 at 17 04 41](https://user-images.githubusercontent.com/22678201/172637061-31a29388-4fe1-4f16-9bf1-b07d0a3011d7.png)

`uffizzi_chaos_exit_until_nginx` should not be failed
