### ISSUE TITLE
Accept additional hostnames within compose file.

### ISSUE THREAD

**Issue by axisofentropy** [UffizziCloud/uffizzi#257]
Child of https://github.com/UffizziCloud/uffizzi_platform/issues/239#issuecomment-1244492724

Some of our customers need to test additional subdomains pointed to the same Uffizzi Deployment. We should accept these within our compose file along with other Uffizzi configuration.

Example:
```
x-uffizzi:
  ingress:
    service: app
    port: 80
    additional_subdomains:
      - "example"
      - "example-hostname"
```

This configuration should be stored with other Uffizzi Deployment configuration and passed along to the controller. The controller will change its behavior if any number of additional hostnames are specified.

Include input validation, error handling, and documentation for this new feature!
