### ISSUE TITLE
Escape env var substitution for env vars passed with an extra `$`, eg: `$$UFFIZZI_URL`

### ISSUE THREAD

**Issue by waveywaves** [UffizziCloud/uffizzi#261]
**Describe the bug**
When passing `ENDPOINT=$$UFFIZZI_URL node start` as a value in the docker-compose `command` spec, `$$UFFIZZI_URL` is not escaped. 
https://stackoverflow.com/questions/40447029/docker-compose-environment-variable-for-command

**Expected behavior**
`$$UFFIZZI_URL` is not set during parsing the docker-compose an d is escaped instead. 
Instead `$UFFIZZI_URL` is then picked up from the container.

**Additional context**
This is a workaround for https://github.com/UffizziCloud/uffizzi_app/issues/251

**Comment by waveywaves** [comment]
docker-compose
```
command: "ENDPOINT=$$UFFIZZI_URL node start"
```

kubernetes manifest 
```
container:
  command: "ENDPOINT=$UFFIZZI_URL node start"

```

**Comment by gadkins** [comment]
Docker Docs reference:
https://docs.docker.com/compose/compose-file/#variable-substitution

**Comment by waveywaves** [comment]
@moklidia here you go
```
# This compose file is for demonstration only, do not use in prod.
version: "3.9"

x-uffizzi:
  ingress:
    service: app
    port: 3001

services:
  app:
    depends_on:
      - "postgres"
    image: "${APP_IMAGE}"
    ports:
      - 3001:3001
    environment:
      ALL_YES: 1
      NO_INQUIRY: 0
      TRUST_PROXY_HEADER: 1
      DB_URL_DEFAULT: postgres://postgres:p0stgr3s@localhost:5432
    deploy:
      resources:
        limits:
          memory: 2000M
   command:  "ENDPOINT=$$UFFIZZI_URL node start"

  postgres:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr3s"
    deploy:
      resources:
        limits:
          memory: 500M
```

**Comment by zipofar** [comment]
@waveywaves  I try to reproduce this case and it works
```


version: '3'

services:
  app:
    build:
      context: https://github.com/zipofar/test_node
      dockerfile: Dockerfile
    entrypoint: /bin/bash
    command:
      - "-c"
      - "ENDPOINT=$$UFFIZZI_URL node /app/app/app.js"

x-uffizzi:
  ingress:
    service: app
    port: 80

  continuous_preview:
    delete_preview_after: 10h
 ```
 
![SCR-20221116-nwv-2](https://user-images.githubusercontent.com/22678201/202207407-fdb75296-b58a-44f3-8f32-95b9e443f148.png)

 I think this problem was because we should set `entrypoint` and set `command` like example above. It looks like the `command` prop does not user friendly at this moment.
