### ISSUE TITLE
Expose multiple ports from a service

### ISSUE THREAD

**Issue by waveywaves** [UffizziCloud/uffizzi#288]
**Tell us about your request**
Based on the [requirements for an integration PoC for Meilisearch](https://github.com/meilisearch/meilisearch/discussions/2883#discussioncomment-3869311) I want to be able to expose two ports from the container. One port will be the terminal accessible from the browser and the other will be the port from where the service itself can be accessed from. 

**Which service(s) is this request for?**
Both

**Describe the solution you'd like**
A configuration in the docker-compose would be hopefully future proof would look like.
```
x-uffizzi:
  ingress:
    service: meilisearch
    port: 7681 # default port 
  expose:
  - service: meilisearch
    ports:
    - "3000:7700"
  - service: frontend
    ports:
    - "3001:7700" 
```
In the above `ingress` spec would cover the default endpoint. UFFIZZI_URL:80 will point to this.
The `expose` spec is a list which would contain other services/ports to be exposed. In the above example, the first service is the same default service exposed at `ingress` but the container is different. The `ports` directive will give all the ports exposed from the container. It should be possible to forward requests from one port exposed on the ingress to a different port on the container. In this case requests coming to UFFIZZI_URL:3000 would be forwarded to the 7700 port of the meilisearch container. Similarly for the next example, requests coming to UFFIZZI_URL:3001 would be forwarded to the 7700 port of the frontend container instead.

**Comment by axisofentropy** [comment]
Are both of these ports serving HTTP? Or other TCP services? UDP?

Uffizzi only supports a single HTTP service. This assumption is baked into our entire stack.

If these are HTTP, you can probably add an HTTP load balancer like `nginx` to multiplex their traffic.  For example, `https://example.app.uffizzi.com/` could go to the `frontend` container and requests for `https://example.app.uffizzi.com/meilisearch/` could go to the other container.

**Comment by gadkins** [comment]
Docker Compose already supports both [`expose`](https://docs.docker.com/compose/compose-file/compose-file-v3/#expose) and [`ports`](https://docs.docker.com/compose/compose-file/compose-file-v3/#ports) syntaxes (See a description of there differences [here](https://stackoverflow.com/questions/40801772/what-is-the-difference-between-docker-compose-ports-vs-expose)). We don't need to nest it under `x-uffizzi`.    

They are both sub-elements of the service definition which can include a list of ports. For example:  

```
myservice:
  image: foo:latest
  ports:
    - "3000"
    - "3000-3005"
    - "8000:8000"
    - "9090-9091:8080-8081"
    - "49100:22"
```

```
myservice:
  image: foo:latest
  expose:
    - "3000"
    - "8000"
```
