### ISSUE TITLE
Image tags with uppercase characters are converted to lowercase.

### ISSUE THREAD

**Issue by axisofentropy** [UffizziCloud/uffizzi#310]
**Describe the bug**
When I specify an image whose `:tag` has uppercase characters, they get converted to lowercase. This prevents the image from successfully pulling.

**To Reproduce**
`docker pull minio/minio:RELEASE.2021-12-18T04-42-33Z`
This shows that this image with uppercase characters in the tag is legitimate.

Specify a Uffizzi Compose file with that image and tag.

**Expected behavior**
The image gets specified in Kubernetes as it is in the compose file.

**Observed behavior**
What ends up in the Kubernetes `Deployment` is `minio/minio:release.2021-12-18t04-42-33z`.

**Comment by NealArw** [comment]
1. Preview deployment does not finish

```
services:
  webhook:
    image: uffizzitest/webhooks-test-app:TEST_UPPERCASE
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhook
  port: 80

x-uffizzi-continuous-preview:
  delete_preview_after: 3h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
```  

![image](https://user-images.githubusercontent.com/89470900/203057174-76728055-6809-4733-b337-c8592aef7901.png)

**Comment by NealArw** [comment]
**TESTED - OK**

```
services:
  webhook:
    image: uffizzitest/webhooks-test-app:TEST_UPPERCASE
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhook
  port: 80

x-uffizzi-continuous-preview:
  delete_preview_after: 3h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
```

```
bash-5.1# bundle exec uffizzi preview create test-compose/uffizzi-compose-webhook-docker-uppercase.yml
Preview with ID deployment-7 was created.
[✔] Creating containers...
Done
[✔] Deploying preview...
  [✔] webhooks-test-app
Done
https://deployment-7-default-ufl3z6.app.qa-gke.uffizzi.com
```
