### ISSUE TITLE
Show error from container registries

### ISSUE THREAD

**Issue by zipofar** [UffizziCloud/uffizzi#316]
For example: when image not found user wants to see expanded error
When we check image availability `def image_available?(credential, image_data)`
We should improve errors for all type of registries

It should looks good for GHA and Uffizzi platform

```"status": 404,
"result": {
  "errors": [
    {
      "code": "MANIFEST_UNKNOWN",
      "message": "manifest unknown",
      "detail": {
        "Tag": "60d"
      }
    }
  ]
}
```

We should improve this message: example for UI (at this moment)
![Screenshot 2022-11-23 at 19 11 38](https://user-images.githubusercontent.com/22678201/203594957-5872505b-f904-491a-9e08-15cce5cbe44c.png)

**Comment by moklidia** [comment]
Let's limit the scope of this issue to DockerHub and DockerRegistry

**Comment by NealArw** [comment]
1.
- Do not connect docker hub integration

Try to add compose file with image from docker hub private repo:

**Result:**

```
bash-5.1# bundle exec uffizzi project compose set -f test-compose/uffizzi-compose-webhook-docker-private.yml
undefined method `split' for ["Container registry returned a 404 error"]:Array
```

```
services:
  webhooks-test-app:
    image: uffizzitest/test-private-repo:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks-test-app
  port: 80

x-uffizzi-continuous-preview:
  delete_preview_after: 1h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
```
