### ISSUE TITLE
Fix error header OCI for docker registry

### ISSUE THREAD

**Issue by zipofar** [UffizziCloud/uffizzi#364]
Error: `MANIFEST_UNKNOWN","message":"OCI index found, but accept header does not support OCI indexes`

TestCase:
```
version: '3'

x-uffizzi:
  ingress:
    service: backstage
    port: 7007

services:
  backstage:
    image: 'registry.uffizzi.com/8aed3d1a-9e28-48c8-bcd8-61a40d825fa6:60d'

    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      NODE_ENV: production
    deploy:
      resources:
        limits:
          memory: 500M
    entrypoint: '/bin/sh'
    command:
      - '-c'
      - "APP_CONFIG_app_baseUrl=$$UFFIZZI_URL APP_CONFIG_backend_baseUrl=$$UFFIZZI_URL APP_CONFIG_auth_environment='production' node packages/backend --config app-config.yaml"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
```
