### ISSUE TITLE
Service name require RFC 1123

### ISSUE THREAD

**Issue by zipofar** [UffizziCloud/uffizzi#389]
Add parsing error if service name does not match RFC regexp
Service name should be a lowercase RFC 1123
```
metadata:
  annotations:
    errors: 'Deployment.apps "app-deployment-18080" is invalid: [spec.template.spec.hostAliases.hostnames:
      Invalid value: "celery_worker": a lowercase RFC 1123 subdomain must consist
      of lower case alphanumeric characters, ''-'' or ''.'', and must start and end
      with an alphanumeric character (e.g. ''example.com'', regex used for validation
      is ''[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'')
```

**Comment by NealArw** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/225845563-cb4b8627-dd6a-4192-808e-ee8a223f9def.png">

**Comment by NealArw** [comment]
👉 1. Can add file with service name with uppercase letters

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/225846423-90e976e1-e3ec-42bb-a08f-4c4757f6469c.png">

**Comment by NealArw** [comment]
2. Can't add file with `.` in the service name

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/225847282-005e275f-5c9d-4758-adaf-91d40eec3768.png">

```


services:
  h.ello-world:
    build: 
      context: https://github.com/NealArw/hello-world-1
      dockerfile: /Dockerfile
      args:
        testarg: uffizzi_test

x-uffizzi:
  ingress:
    service: h.ello-world
    port: 80
    
  continuous_preview:
    share_to_github: true
    delete_preview_after: 1h
    delete_preview_when_pull_request_is_closed: true
    deploy_preview_when_pull_request_is_opened: true
```
